ODROID-M1: fix compile error due to redefined symbol 'DRM_FORMAT_MOD_ARM_AFBC'
cc -Igst/rkximage/1d227f6@@gstrkximage@sha -Igst/rkximage -I../gst/rkximage -I. -I../ -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/orc-0.4 -I/usr/include/libdrm -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -fvisibility=hidden -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -DG_DISABLE_DEPRECATED '-DUNUSED=__attribute__((unused))' -Wall -Werror -g -O2 -fdebug-prefix-map=/home/odroid/gstreamer-rockchip=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -DHAVE_CONFIG_H -MD -MQ 'gst/rkximage/1d227f6@@gstrkximage@sha/ximagesink.c.o' -MF 'gst/rkximage/1d227f6@@gstrkximage@sha/ximagesink.c.o.d' -o 'gst/rkximage/1d227f6@@gstrkximage@sha/ximagesink.c.o' -c ../gst/rkximage/ximagesink.c
In file included from ../gst/rkximage/ximagesink.c:26:
/usr/include/libdrm/drm_fourcc.h:887: error: "DRM_FORMAT_MOD_ARM_AFBC" redefined [-Werror]
  887 | #define DRM_FORMAT_MOD_ARM_AFBC(__afbc_mode) \
      |
In file included from ../gst/rkximage/ximagesink.c:15:
../gst/rkximage/gstkmsutils.h:54: note: this is the location of the previous definition
   54 | #define DRM_FORMAT_MOD_ARM_AFBC(__afbc_mode) fourcc_mod_code(ARM, __afbc_mode)
      |
In file included from ../gst/rkximage/ximagesink.c:26:
/usr/include/libdrm/drm_fourcc.h:936: error: "AFBC_FORMAT_MOD_SPARSE" redefined [-Werror]
  936 | #define AFBC_FORMAT_MOD_SPARSE  (1ULL <<  6)
      |
In file included from ../gst/rkximage/ximagesink.c:15:
../gst/rkximage/gstkmsutils.h:62: note: this is the location of the previous definition
   62 | #define AFBC_FORMAT_MOD_SPARSE (((__u64)1) << 6)
      |
cc1: all warnings being treated as errors

Signed-off-by: Dongjin Kim <tobetter@gmail.com>